### ISSUE TITLE
Use this for MeshGraphormer?

### ISSUE THREAD

**Issue by andupotorac** [OllieBoyne/Foot3D#1]
Hi Ollie. I was wondering if this could be used to train https://github.com/microsoft/MeshGraphormer for feet. The reason is that it's been adapted in HandRefiner, which now helps with solving Generative AI hands: https://github.com/wenquanlu/HandRefiner.

But feet are still an unsolved issue, so I wondered if your work might help address that.

**Comment by OllieBoyne** [comment]
Hi!

Yes, this looks interesting! You will probably need to produce some kind of paired image & 3D data at scale. The data in this repo is designed for (a) just 3D training, or (b) evaluating 3D reconstruction - there aren't enough 2D image examples for proper training.

My suggestion would be to look at our [SynFoot](https://github.com/OllieBoyne/SynFoot) project instead for paired 2D/3D labels.
