### ISSUE TITLE
right  foot

### ISSUE THREAD

**Issue by li1u** [OllieBoyne/Foot3D#3]
Hi, I want to know why the effect on the right foot is not good. I have retrained the model.Set left_only to false

**Comment by li1u** [comment]
![image](https://github.com/user-attachments/assets/88fbc609-628f-4cdf-978e-8e84afd70273)
![image](https://github.com/user-attachments/assets/3dba5985-1726-4f6b-9ed0-e94538c36cb1)
This is the result of my left and right feet. My right foot also tends to turn like left foot.

**Comment by OllieBoyne** [comment]
Hi, this repo is for the Foot3D dataset. Please could you repost the issue on the correct repo, along with some more details about the process you used? Thanks.
